# Generated by Django 2.1.5 on 2020-02-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20200204_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
